[build]
  command = "npm run build"  # or your respective build command
  publish = "build"  # or the correct directory where your build output is stored

[context.production.environment]
  NETLIFY_USE_FOCAL = "true"
